export const REQUEST_SEARCH_RESULT = 'REQUEST_SEARCH_RESULT'

export const GET_SEARCH_RESULT_BY_NAME = 'GET_SEARCH_RESULT_BY_NAME'
export const GET_SEARCH_RESULT_BY_PERSON = 'GET_SEARCH_RESULT_BY_PERSON'

export const SWITCH_SEARCH = 'SWITCH_SEARCH'
export const SET_SORT_BY_DATE = 'SET_SORT_BY_DATE'