// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bottomPageHeadWrapper: string;
  canSee: string;
  logoFooterContainer: string;
  mainContainer: string;
  mainPageContentWrapper: string;
  mainPageFooter: string;
  mainWrapper: string;
  rightTextBottomPageHead: string;
  searchResultContainer: string;
  selectedSortByRating: string;
  selectedSortByReleaseDate: string;
  sortByRating: string;
  sortByReleaseDate: string;
  textBottomPageHead: string;
  textBottomPageHeadWrapper: string;
  topPageHeadBackgroundImg: string;
  valueFoundLeftTextBottonPageHead: string;
  wrapperContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
